# apiVersion: gateway.networking.k8s.io/v1
# kind: GatewayClass
# metadata:
#   name: traefik
# spec:
#   controllerName: example.com/gateway-controller
# ---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: lara-gateway
  namespace: cloud
spec:
  gatewayClassName: traefik
  listeners:
  - name: http
    protocol: HTTP
    port: 8000 # default traefik HTTP port
    hostname: "*.cloud.bonfimalan.com.br"
  - name: https
    protocol: HTTPS
    port: 8443 # 443
    hostname: "*.cloud.bonfimalan.com.br"
    tls:
      certificateRefs:
        - name: cloud-tls
          namespace: cloud
  infrastructure:
    annotations:
      traefik.ingress.kubernetes.io/forwarded-headers: "true"
      traefik.ingress.kubernetes.io/enable-forwarded-headers: "true"

  # - name: https # TODO add the TLS support
  #   protocol: HTTPS
  #   port: 8443         # Traefik HTTPS default port, adjust as needed
  #   tls:
  #     mode: Terminate
  #     certificateRefs:
  #       - name: traefik-tls-secret
  #         namespace: default

# TODO create namespaces