# Keycloak database
apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres
  namespace: cloud
  labels:
    app: keycloak-postgres
spec:
  clusterIP: None
  selector:
    app: keycloak-postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak-postgres
  namespace: cloud
spec:
  replicas: 1
  serviceName: "keycloak-postgres"
  selector:
    matchLabels:
      app: keycloak-postgres
  template:
    metadata:
      labels:
        app: keycloak-postgres
    spec:
      containers:
        - name: keycloak-postgres
          image: bitnami/postgresql@sha256:f90843c055d10ba444f727fc0a9433a5b67d76630a3dea03570b56c3bc8e01fc
          resources:
            limits:
              memory: "256Mi"
              cpu: "0.5"
            requests:
              memory: "128Mi"
              cpu: "0.2"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-postgres-secret
                  key: POSTGRESQL_PASSWORD
            - name: POSTGRESQL_USERNAME
              value: keycloak-user
            - name: POSTGRESQL_DATABASE
              value: keycloak-database
          volumeMounts:
            - name: keycloak-postgres-storage
              mountPath: /bitnami/postgresql
  volumeClaimTemplates:
    - metadata:
        name: keycloak-postgres-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 8Gi
# Keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -z keycloak-postgres 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:26.3.2
        args:
          - "start"
        resources:
          limits:
            memory: "1024Mi"
            cpu: "0.5"
          requests:
            memory: "512Mi"
            cpu: "0.2"
        env:
          - name: KEYCLOAK_ADMIN
            valueFrom:
              secretKeyRef:
                name: keycloak-secrets
                key: KEYCLOAK_ADMIN
          - name: KEYCLOAK_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-secrets
                key: KEYCLOAK_ADMIN_PASSWORD
          - name: KC_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-postgres-secret
                key: POSTGRESQL_PASSWORD
          - name: KC_DB
            value: postgres
          - name: KC_HTTP_ENABLED
            value: "true"
          - name: 'KC_DB_URL_DATABASE'
            value: 'keycloak-database'
          - name: 'KC_DB_URL_HOST'
            value: 'keycloak-postgres'
          - name: KC_DB_USERNAME
            value: keycloak-user
          - name: KC_PROXY
            value: "edge"
          - name: KC_HOSTNAME_STRICT_HTTPS
            value: "true"
          - name: KC_HOSTNAME
            value: https://auth.cloud.bonfimalan.com.br
          - name: KC_FRONTEND_URL
            value: https://auth.cloud.bonfimalan.com.br
          - name: KC_PORXY_HEADERS
            value: forwarded
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: cloud
spec:
  type: ClusterIP
  selector:
    app: keycloak
  ports:
    - port: 80
      targetPort: 8080
