apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloak-admins
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keycloak-admins-binding
subjects:
  - kind: Group
    name: keycloak-admins
roleRef:
  kind: ClusterRole
  name: keycloak-admins
  apiGroup: rbac.authorization.k8s.io