#cloud-config
package_update: true
package_upgrade: false
packages:
  - nginx
  - qemu-guest-agent

runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - systemctl enable nginx
  - systemctl start nginx
  - echo "<h1>Hello from $(hostname) via cloud-init 🐧</h1>" > /var/www/html/index.nginx-debian.html
